### ISSUE TITLE
Delete a row by key

### ISSUE THREAD

**Issue by jfreites** [taimoorgit/redis-object-storage#1]
There is a way, using this implementation, to delete a row in the table passing an key:value? Example:

The row has id, name and email.

Can I delete a specific row by a matching email? Right now I think to iterate for every element in the hash and when I found the match delete it.

**Comment by taimoorgit** [comment]
Hi, thanks for asking. 

I have been looking into this and I haven't been able to find a way to get a hash by searching for a string in Redis. So you wouldn't be able to fetch/delete by email, but you would be able to via the user ID (assuming it is an integer). 

Related Stackoverflow discussion: https://stackoverflow.com/questions/11470468/how-to-search-in-redis-for-hash-keys/11471258

That being said, I'll push a change to add delete by key ID soon.

**Comment by jfreites** [comment]
I understand. Thank you!

**Comment by taimoorgit** [comment]
@jfreites I added the feature you requested - you can now query by string fields in addition to integer fields. I made a big refactor adding a couple data types for this library too. 

How it works:

1. When you insert a hash (database row), you can specify which keys (table columns) in that hash should be indexed.
2. The library will add an index in the table for that hash using an unordered set
3. You can search for hashes using an indexed column (including strings) by using [`SINTER`](https://redis.io/commands/sinter)

[Here's some example code that implements a shopping cart.](https://github.com/taimoorgit/redis-object-storage/blob/master/src/example.ts) At the bottom of the file I am using a set intersection searching for a hash (database row) that has a key (column) with a value equal to "Logitech BRIO". You could do the same for a user's email address using something like: `sinter user_table.email=taimooraug@gmail.com`

Let me know if this helps! 

[By the way, I have also published a beta version of this package to NPM](https://www.npmjs.com/package/redis-object-storage)
